---
title: "2018/02/06 花蓮地震"
author: "Person"
output:
  html_document:
    df_print: paged
---
```{r data&library, echo=FALSE, warning=FALSE, include=FALSE}
#load library
library(dplyr)
library(rgdal)
library(leaflet)
library(geosphere)
library(htmlwidgets)
library(xtable)
library(knitr)
library(mapview)
library(ggmap)
library(automap)
library(here)
library(XML)

#function
read.cwbsgm.index <- function(file.name){
  a <- readLines(con <- file(file.name))
  #station
  b <- textConnection(a[!grepl("^[0-9]",a)])
  #DF <- read.table(b, fill = TRUE, stringsAsFactors=FALSE)
  DF <- read.fwf(b, widths=c(7,2,8,8,7,7,6,13,5,16,6), stringsAsFactors=FALSE, strip.white=TRUE)
  #DF <- trim(DF)
  close(b)
  names(DF) <- c("Sta", "Intensity", "Distance", "PGA.Z", "PGA.NS", "PGA.EW", "Time.elapse", "File.name",
                 "Instrument", "first.time", "A1")
  DF$PGA.Z <- as.numeric(DF$PGA.Z)
  DF$PGA.NS <- as.numeric(DF$PGA.NS)
  DF$PGA.EW <- as.numeric(DF$PGA.EW)
  DF$first.time <- as.character(DF$first.time)
  #earthquake
  b <- textConnection(a[grepl("^[0-9]",a)])
  DF2 <- read.fwf(b, widths=c(4,2,2,2,2,6,2,5,3,5,6,4,3,4,3,4,4,4,2,3,1,13,3), stringsAsFactors=FALSE,
                  strip.white=TRUE)
  #DF2 <- trim(DF2)
  close(b)
  close(con)
  names(DF2) <- c("Year", "Month", "Day", "Hour", "Minute", "Sec", "Lat", "Lat.min", "Lon", "Lon.min", 
                  "Depth", "ML", "Sta.num", "closest.epi", "angle", "RMS", "ERH", "ERZ","N", "Number.sta",
                  "quality", "Pfile", "Number.records")
  DF2$EQ_ID <- paste(DF2$Year, "_", formatC(DF2$Month, width=2, flag="0"), 
                     formatC(DF2$Day, width=2, flag="0"), "_", 
                     formatC(DF2$Hour, width=2, flag="0"), formatC(DF2$Minute, width=2, flag="0"), "_", 
                     formatC(round(DF2$Sec), width=2, flag="0"), sep="")
  DF2$Lon.X <- DF2$Lon + (DF2$Lon.min/60)
  DF2$Lat.Y <- DF2$Lat + (DF2$Lat.min/60)
  DF3 <-  DF2[rep(1:nrow(DF2), DF2$Number.records),]
  DF.OK <- cbind(DF3,DF)
  DF.OK$file.id <- paste0(DF.OK$Pfile, ".", DF.OK$File.name)
  DF.OK$SGM_ID <- paste(DF.OK$Year, formatC(DF.OK$Month, width=2, flag="0"), 
                        formatC(DF.OK$Day, width=2, flag="0"),  
                        formatC(DF.OK$Hour, width=2, flag="0"), formatC(DF.OK$Minute, width=2, flag="0"),  
                        formatC(round(DF.OK$Sec), width=2, flag="0"), ".", DF.OK$Sta, sep="")
  DF.OK
}


```

# 簡介{.Introduction}

台灣時間2018年02月06日午夜23時50分於台灣花蓮縣近海發生芮氏規模M L 6.0之地震

- 花蓮市、宜蘭南澳皆觀測到7級震度
- 震央位置在北緯24.14度、東經121.69度，震源深度為10.0公里


```{r read data}
file.name <- file.path("..", "data", "CWB", "Index.log")
file.name2 <- file.path("..", "data", "CWB", "Station.log")

sgm.index <- read.cwbsgm.index(file.name)
station.index <- read.table(file.name2, stringsAsFactors = F, 
                            col.names=c("STA_ID", "Sta.lon", "Sta.lat", "Sta.elevation", "Start.time",
                                        "End.time"))
sgm.index.ok <- sgm.index %>% left_join(station.index, by=c("Sta"="STA_ID")) %>% 
  mutate(STA_ID = Sta, PGA.H = sqrt(PGA.NS * PGA.EW)/978.8)
# get eq.info
eq.info <- distinct(sgm.index.ok, EQ_ID, .keep_all = TRUE) %>%
  select(EQ_ID, Pfile, Year:quality, Lon.X, Lat.Y)
# get sta.info
sta.info <- distinct(sgm.index.ok, STA_ID, .keep_all = TRUE) %>%
  select(STA_ID, Sta:End.time) %>%
  mutate(PGA.H = sqrt(PGA.NS * PGA.EW)/978.8)
# convert to sp object
# 台灣常用的 EPSG代碼
# TM2（TWD97，中央經線121度）(適用臺灣本島，目前政府使用) ＝> EPSG:3826
# TM2（TWD67，中央經線121度）(適用臺灣本島，早期政府使用) ＝> EPSG:3828
# WGS84經緯度（全球性資料，如：GPS） ＝> EPSG:4326
eq.sp <- as.data.frame(eq.info)
coordinates(eq.sp) <- ~Lon.X+Lat.Y
proj4string(eq.sp) <- CRS("+init=epsg:4326")
sta.sp <- sta.info
coordinates(sta.sp) <- ~Sta.lon+Sta.lat
proj4string(sta.sp) <- CRS("+init=epsg:4326")
sgm.sp <- sgm.index.ok
coordinates(sgm.sp) <- ~Sta.lon+Sta.lat
proj4string(sgm.sp) <- CRS("+init=epsg:4326")

# read active fault 
#以readOGR函數(rgdal package)讀取KML檔案
#資料來源：https://opendata.epa.gov.tw/Data/Details/SOIL00103
#faults <- readOGR("../data/EPA/active_fault.kml", encoding = "UTF-8", stringsAsFactors = FALSE)
fault <- readOGR("../data/EPA/Taiwan_active_fault.shp", stringsAsFactors = FALSE, encoding = "UTF-8")
fault2 <- readOGR("../data/EPA/Taiwan_active_fault.TAB", stringsAsFactors = FALSE)
fault2@data$Name <- unlist(lapply(fault2@data$Name, iconv, from = "Big5", to = "UTF-8"))
#地調所geojson
#http://www.geologycloud.tw/dashboard/datalist
# fault3 <- geojsonio::geojson_read("http://www.geologycloud.tw/api/v1/zh-tw/ActiveFault?t=.json", method=
#                                     "web", what = "sp")
```

#Map

## Leaflet map

```{r leaflet map, echo=FALSE, warning=FALSE, error=FALSE, message=FALSE}
#leaflet map
m <- leaflet() %>%
  addTiles(group = "OSM(default)") %>%
  addProviderTiles("OpenTopoMap", group = "OpenTopo") %>%
  addProviderTiles("Esri.WorldImagery", group = "Esri.WorldImagery") %>%
  addProviderTiles("CartoDB.Positron", group = "CartoDB") %>%
  addProviderTiles("Stamen.Toner", group = "Stamen.Toner") %>%
  addProviderTiles("Stamen.Terrain", group = "Stamen.Terrain") %>%
  addProviderTiles("NASAGIBS.ViirsEarthAtNight2012", group = "NASA.Earth.Night") %>%
  addWMSTiles("http://wms.nlsc.gov.tw/wms", layers = "PHOTO2",
              options = WMSTileOptions(format = "image/png"),
              attribution = "maps.nlsc.gov.tw", group = "TW.Aerial.Photo") %>%
  addCircleMarkers(data = eq.sp, radius = ~1.5^ML, 
                   popup = ~paste(sep="<br/>", "EQ", EQ_ID, paste("ML=", ML),
                                  paste("Depth=", Depth, " km", sep="")),
                   stroke = FALSE, fillOpacity = 0.5, group = "EQ") %>%
  # addMarkers(data = sgm.sp, label = ~STA_ID, popup = ~paste(sep="<br/>", paste("STA=", STA_ID), 
  #                                                           paste("Instrument=", Instrument),
  #                                                           paste("File name=", File.name),
  #                                                           paste("Distance=", Distance, "km"),
  #                                                           paste("Intensity=", Intensity),
  #                                                           paste("PGA.Z=", PGA.Z),
  #                                                           paste("PGA.NS=", PGA.NS),
  #                                                           paste("PGA.EW=", PGA.EW)),
  #            labelOptions = labelOptions(noHide = T), group = "Station") %>%
  addMarkers(data = sgm.sp, label = ~STA_ID, popup = popupTable(sgm.sp@data),
             labelOptions = labelOptions(noHide = T), group = "Station") %>%
  addPolylines(data=fault2, color = "red", popup = ~Name, group = "Faults") %>%
  addLayersControl(
    baseGroups = c("OSM(default)", "OpenTopo", "Esri.WorldImagery", "CartoDB", 
                   "Stamen.Toner", "Stamen.Terrain", "NASA.Earth.Night", "TW.Aerial.Photo"),
    overlayGroups = c("EQ", "Station", "Faults"),
    options = layersControlOptions(collapsed = TRUE)
  )
m
```

## mapview map

```{r mapview map}
# mapview
mapview(sta.sp, zcol = "PGA.H", legend = TRUE) + mapview(eq.sp)


```

## ggmap

```{r ggmap}
# start with points
pred.points <- ggplot(data = sgm.index.ok,
       aes(x = Sta.lon,
           y = Sta.lat,
           colour = PGA.H)) + 
  geom_point()
print(pred.points)

# Binned data
pred.stat <- ggplot(data = sgm.index.ok,
                      aes(x = Sta.lon,
                          y = Sta.lat,
                          z = PGA.H)) + 
  stat_summary2d(fun = mean)
print(pred.stat)

#
YlOrBr <- c("#FFFFD4", "#FED98E", "#FE9929", "#D95F0E", "#993404")
map.in <- get_map(location = c(min(sgm.index.ok$Sta.lon),
                               min(sgm.index.ok$Sta.lat),
                               max(sgm.index.ok$Sta.lon),
                               max(sgm.index.ok$Sta.lat)))
theme_set(theme_bw(base_size = 8))
pred.stat.map <- ggmap(map.in) %+% sgm.index.ok + 
  aes(x = Sta.lon,
      y = Sta.lat,
      z = PGA.H) +
  stat_summary_2d(fun = median, 
                 binwidth = c(.005, .005),
                 alpha = 0.5) + 
  scale_fill_gradientn(name = "Median",
                       colours = YlOrBr,
                       space = "Lab") + 
  labs(x = "Longitude",
       y = "Latitude") +
  coord_map()
print(pred.stat.map)
```

## kirging map

```{r}
# convert project
sgm.sp.twd97tm2 <- spTransform(sgm.sp, CRS("+init=epsg:3826"))


#Setting the  prediction grid properties
min_x = min(sgm.sp.twd97tm2$Sta.lon) #minimun x coordinate
min_y = min(sgm.sp.twd97tm2$Sta.lat) #minimun y coordinate
x_length = max(sgm.sp.twd97tm2$Sta.lon - min_x) #easting amplitude
y_length = max(sgm.sp.twd97tm2$Sta.lat - min_y) #northing amplitude
cellsize = 100 #pixel size
ncol = round(x_length/cellsize,0) #number of columns in grid
nrow = round(y_length/cellsize,0) #number of rows in grid

# coordinates(meuse) = ~x+y
# proj4string(meuse) = CRS("+proj=utm +ellps=WGS84 +datum=WGS84") #assign CRS with projected coordinates.

grid = GridTopology(cellcentre.offset=c(min_x,min_y),cellsize=c(cellsize,cellsize),cells.dim=c(ncol,nrow))

#Convert GridTopolgy object to SpatialPixelsDataFrame object.
grid = SpatialPixelsDataFrame(grid,
                              data=data.frame(id=1:prod(ncol,nrow)),
                              proj4string=CRS(proj4string(sgm.sp.twd97tm2)))

#Perform ordinary kriging and store results inside object of type "autoKrige" "list" 
kriging_result = autoKrige(PGA.H~1, sgm.sp.twd97tm2, grid)
plot(kriging_result)
prediction_PGA.H = kriging_result$krige_output

plot(kriging_result$krige_output, breaks = c(0, 0.8,2.5,8,25,80,250,400,999)/980, 
     col= colorRampPalette(brewer.pal(5,"YlOrRd"))(8))
```


